/*
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/076aec57-a5d0-4107-aff0-c9179d08a8cd 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  String status;
  float temp;
  int blood_Oxygen;
  int heart_Rate;
  bool fall;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  
}

/*
  Since HeartRate is READ_WRITE variable, onHeartRateChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onHeartRateChange()  {
  // Add your code here to act upon HeartRate change
}

/*
  Since BloodOxygen is READ_WRITE variable, onBloodOxygenChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onBloodOxygenChange()  {
  // Add your code here to act upon BloodOxygen change
}

/*
  Since Status is READ_WRITE variable, onStatusChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onStatusChange()  {
  // Add your code here to act upon Status change
}

/*
  Since Fall is READ_WRITE variable, onFallChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onFallChange()  {
  // Add your code here to act upon Fall change
}

/*
  Since Temp is READ_WRITE variable, onTempChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onTempChange()  {
  // Add your code here to act upon Temp change
}