// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "2427e559-23e8-4b92-ab2f-55328d40047b";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onStatusChange();
void onTempChange();
void onBloodOxygenChange();
void onHeartRateChange();
void onFallChange();

String status;
float temp;
int blood_Oxygen;
int heart_Rate;
bool fall;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(status, READWRITE, ON_CHANGE, onStatusChange);
  ArduinoCloud.addProperty(temp, READWRITE, ON_CHANGE, onTempChange);
  ArduinoCloud.addProperty(blood_Oxygen, READWRITE, ON_CHANGE, onBloodOxygenChange);
  ArduinoCloud.addProperty(heart_Rate, READWRITE, ON_CHANGE, onHeartRateChange);
  ArduinoCloud.addProperty(fall, READWRITE, ON_CHANGE, onFallChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);